##############################################
# Web server                                 #
##############################################
server.port=${API_APPLICATION_PORT:8078}
server.servlet.context-path=${API_CONTEXT_PATH:/api}
cors.allowed-origins=${API_ALLOWED_ORIGINS:http://localhost:4199}


##############################################
# Keycloak oauth2 resource server            #
##############################################
keycloak.auth-server-url=${API_KEYCLOAK_SERVERURL:http://localhost:8091/auth}
spring.security.oauth2.resourceserver.jwt.issuer-uri= ${keycloak.auth-server-url}/realms/${API_KEYCLOAK_REALM:uk-pmrv}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


##############################################
# Unauthenticated APIs                       #
##############################################
security.unauthenticated-apis=/v3/api-docs/**,/error,/swagger-ui/**,/swagger-resources/**,/configuration/**,/ui-configuration/**,/webjars/**,/actuator/**

##############################################
# Logging                                    #
##############################################
logging.level.uk.gov=${API_LOG_LEVEL:DEBUG}
spring.jpa.open-in-view=false
logging.config=${LOG4J2_CONFIG_FILE:classpath:log4j2-json.xml}

#Comma-separated list of uri patterns to be excluded from logging (eg /api/v1.0/*)
rest.logging.excludedUriPatterns=/swagger,/api-docs,/configuration,/webjars,/actuator
rest.logging.level=${REST_LOGGING_LEVEL:INFO}


##############################################
# Jackson                                    #
##############################################
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=true


##############################################
# Actuator                                   #
##############################################
management.endpoints.web.exposure.include=info, metrics, health


##############################################
# Cookies settings                           #
##############################################
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true


###############################################
# Cloudwatch                                  #
###############################################
cloudwatch.enabled=${CLOUDWATCH_METRICS_ENABLED:false}
cloudwatch.namespace=${CLOUDWATCH_METRICS_NAMESPACE:etsgw-api}
cloudwatch.batchSize=${CLOUDWATCH_METRICS_BATCHSIZE:10}
cloudwatch.step=${CLOUDWATCH_METRICS_STEP:PT1M}
cloudwatch.region=${AWS_DEFAULT_REGION:eu-west-2}
cloudwatch.accessKey=${AWS_ACCESS_KEY_ID:test}
cloudwatch.secretKey=${AWS_SECRET_ACCESS_KEY:test}
cloudwatch.awsEndpointUrl=${CLOUDWATCH_METRICS_AWSENDPOINTURL:https://monitoring.eu-west-2.amazonaws.com}


###############################################
# Swagger                                     #
###############################################
springdoc.api-docs.enabled=${API_SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${API_SWAGGER_ENABLED:true}
springdoc.model-converters.polymorphic-converter.enabled=true
springdoc.remove-broken-reference-definitions=false


###############################################
# UI features                                 #
###############################################
ui.analytics.measurementId=${ANALYTICS_MEASUREMENTID:}
ui.analytics.propertyId=${ANALYTICS_PROPERTYID:}
ui.keycloakServerUrl= ${keycloak.auth-server-url}
ui.features.installationAviationEnabled=${FEATURES_INSTALLATION_AVIATION_ENABLED:true}
ui.features.maritimeEnabled=${FEATURES_MARITIME_ENABLED:true}