/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './contentDisposition';
import { ErrorResponseHeadersAcceptLanguageInner } from './errorResponseHeadersAcceptLanguageInner';
import { ErrorResponseHeadersContentLanguage } from './errorResponseHeadersContentLanguage';
import { ErrorResponseHeadersHost } from './errorResponseHeadersHost';
import { MediaType } from './mediaType';

export interface ErrorResponseHeaders {
  [key: string]: Array<string> | any;

  acceptCharset?: Array<string>;
  contentDisposition?: ContentDisposition;
  allow?: Array<object>;
  origin?: string;
  empty?: boolean;
  location?: string;
  host?: ErrorResponseHeadersHost;
  all?: { [key: string]: string };
  lastModified?: number;
  date?: number;
  contentLength?: number;
  range?: Array<object>;
  cacheControl?: string;
  contentLanguage?: ErrorResponseHeadersContentLanguage;
  etag?: string;
  accept?: Array<MediaType>;
  accessControlAllowOrigin?: string;
  accessControlAllowMethods?: Array<object>;
  accessControlAllowHeaders?: Array<string>;
  accessControlExposeHeaders?: Array<string>;
  accessControlAllowCredentials?: boolean;
  accessControlMaxAge?: number;
  accessControlRequestMethod?: object;
  accessControlRequestHeaders?: Array<string>;
  acceptPatch?: Array<MediaType>;
  acceptLanguage?: Array<ErrorResponseHeadersAcceptLanguageInner>;
  basicAuth?: string;
  acceptLanguageAsLocales?: Array<ErrorResponseHeadersContentLanguage>;
  bearerAuth?: string;
  connection?: Array<string>;
  expires?: number;
  ifMatch?: Array<string>;
  ifNoneMatch?: Array<string>;
  ifUnmodifiedSince?: number;
  pragma?: string;
  upgrade?: string;
  vary?: Array<string>;
  ifModifiedSince?: number;
  contentType?: MediaType;
}
