/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseHeaders } from './errorResponseHeaders';
import { HttpStatusCode } from './httpStatusCode';
import { ProblemDetail } from './problemDetail';

export interface ErrorResponse {
  statusCode?: HttpStatusCode;
  body?: ProblemDetail;
  detailMessageArguments?: Array<object>;
  typeMessageCode?: string;
  detailMessageCode?: string;
  titleMessageCode?: string;
  headers?: ErrorResponseHeaders;
}
