/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ErrorResponseHeadersContentLanguage {
  language?: string;
  displayName?: string;
  country?: string;
  variant?: string;
  script?: string;
  unicodeLocaleAttributes?: Array<string>;
  unicodeLocaleKeys?: Array<string>;
  displayLanguage?: string;
  displayScript?: string;
  displayCountry?: string;
  displayVariant?: string;
  extensionKeys?: Array<string>;
  iso3Language?: string;
  iso3Country?: string;
}
