/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseHeadersHostAddress } from './errorResponseHeadersHostAddress';

export interface ErrorResponseHeadersHost {
  address?: ErrorResponseHeadersHostAddress;
  port?: number;
  unresolved?: boolean;
  hostName?: string;
  hostString?: string;
}
