/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ErrorResponseHeadersHostAddress {
  hostAddress?: string;
  address?: Array<string>;
  hostName?: string;
  linkLocalAddress?: boolean;
  multicastAddress?: boolean;
  anyLocalAddress?: boolean;
  loopbackAddress?: boolean;
  siteLocalAddress?: boolean;
  mcglobal?: boolean;
  mcnodeLocal?: boolean;
  mclinkLocal?: boolean;
  mcsiteLocal?: boolean;
  mcorgLocal?: boolean;
  canonicalHostName?: string;
}
