/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationAlertDTO } from './notificationAlertDTO';

export interface UIPropertiesDTO {
  features?: { [key: string]: boolean };
  analytics?: { [key: string]: string };
  keycloakServerUrl?: string;
  notificationAlerts?: Array<NotificationAlertDTO>;
}
